# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-03-12 17:16
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=32, null=True)),
                ('content', models.TextField(blank=True, max_length=256, null=True)),
            ],
        ),
    ]
