# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-03-12 17:59
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='content',
            field=models.CharField(blank=True, max_length=256, null=True),
        ),
    ]
