# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-03-22 19:17
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='post',
            old_name='short_discription',
            new_name='short_description',
        ),
    ]
