# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-04-08 11:10
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0004_auto_20170408_1558'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='comment_counter',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
