# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-04-26 04:51
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0005_post_comment_counter'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='comment_counter',
        ),
    ]
