# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-05-04 14:27
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0008_auto_20170504_1116'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='keyword',
            unique_together=set([('tag', 'post')]),
        ),
    ]
