# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-04-29 07:27
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Telephone',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_name', models.CharField(max_length=256)),
                ('phone', models.CharField(max_length=256)),
                ('created_date', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
